theme: jekyll-theme-minimal
title: Tori's Portfolio Landing Page
description: |
   Welcome to my portfolio! This is a live page for projects related to engineering and emerging technologies. I enjoy building practical projects to engage with technologies of interest.
