theme: jekyll-theme-minimal
title: Tori's Project Landing Page
description: |
   Welcome to my portfolio! This is a live page to log and track my engineering projects. I enjoy building practical systems to engage with emerging technologies of interest.
